services:
  backend:
    build: ./backend
    container_name: electolibrary-backend
    ports:
      - "8000:8000"
    volumes:
      # Том для БД — переживает пересборки контейнера
      - ./data:/app/data
      # Том для загруженных обложек
      - ./uploads:/app/uploads
    networks:
      - elib-net

  frontend:
    build: ./frontend
    container_name: electolibrary-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - elib-net

networks:
  elib-net:
    driver: bridge